wskr_floor:
  ros__parameters:
    resize_width: 640
    resize_height: 360
    blur_kernel_size: 9
    bottom_sample_fraction: 0.5
    bottom_sample_height_fraction: 0.25
    morph_kernel_size: 5
    val_range: 40
    color_distance_threshold: 17
    gradient_threshold: 96
    highlight_thresh: 230
