wskr_floor:
  ros__parameters:
    resize_width: 1920
    resize_height: 1080
    blur_kernel_size: 33
    bottom_sample_fraction: 0.5
    bottom_sample_height_fraction: 1.0
    morph_kernel_size: 31
    val_range: 106
    color_distance_threshold: 13
    gradient_threshold: 758
    highlight_thresh: 254
